sozialhelden/accessibility-cloud

client/pages/sources/show/overview/map.js

How to reproduce:
* View a single place on the map
* Close the sidebar on the left
* Click on "view all"
Expected result: All places should be fetched and displayed on the map

Cast query parameter to Number so that numerical comparison can work

---

client/stylesheets/base.less
client/stylesheets/components.import.less

This fixes https://trello.com/c/LaqsCylf/313-fix-markdown-lists-not-appearing-with-numbers:

Markdown formatting

---

client/pages/sources/show/sidebar/charts/boolean.js
client/pages/sources/show/sidebar/top-stats.html

3 little fixes for the source overview sidebar

---

both/api/source-imports/server/privileges.js
both/api/sources/server/stream-chain/control-import.js
client/pages/sources/show/source-imports/imports.html
client/stylesheets/components.import.less

Adds a new section to the import history:

Show originally used stream chain in import

---

both/api/sources/server/stream-chain/stream-types/http-download.js
both/api/sources/server/stream-chain/stream-types/transform-data.js
both/api/sources/server/stream-chain/stream-types/upsert-place.js
client/pages/sources/show/format/format.less
client/pages/sources/stream-chain/components/multi-http-download.js

More changes and small bugfixes for issues that happened when creating a new data source for import Wheelmap data over API.

Nicer stream chain IDE pt. 2

---

client/pages/sources/show/source-imports/imports.js

Nothing too fancy. You don't have to check this out for testing I guess ;)

Show latest import when opening import history

---

both/api/organizations/privileges.js
both/api/source-imports/server/privileges.js
both/api/source-imports/server/publications.js
both/api/source-imports/source-imports.js
both/api/sources/server/privileges.js
both/api/sources/server/publications.js
both/api/sources/server/stream-chain/control-import.js
both/api/sources/server/stream-chain/stream-chain.js
both/api/sources/sources.js
client/components/source/source.js
client/pages/sources/show/format/format.js
client/pages/sources/show/header/show-header-sub.html
client/pages/sources/show/overview/show.js
client/pages/sources/show/sidebar/attributes.html
client/pages/sources/show/sidebar/attributes.js
client/pages/sources/show/sidebar/charts/activity.js
client/pages/sources/show/source-imports/imports.js
client/routes.js

This fixes many little issues that mostly happened around using the site with foreign sources or as non-logged in user. They appear now because I tried to create user stories for the screencast from the perspective of a completely new user. I hope we'll get to the ChimpJS integration tests soon…

Fix broken privileges and little issues when using the site as a new user

---

both/api/sources/server/stream-chain/stream-types/http-download.js
both/api/sources/server/stream-chain/stream-types/transform-data/get-helpers-content.js
both/api/sources/server/stream-chain/stream-types/transform-data/get-helpers-content.test.js
both/api/sources/server/stream-chain/stream-types/transform-data/get-vm-context.js
docs/importing-data.md
private/transform-helpers/convert-osgb36-to-wgs84-point.js
private/transform-libs/geodesy.js

- Add a helper function for converting OSGB36 coordinates into a GeoJSON point
- Add [geodesy library](https://github.com/chrisveness/geodesy) from @chrisveness

Add OSGB36 coordinate support

---

both/api/global-stats/global-stats.js
both/api/global-stats/server/calculation.js
both/api/global-stats/server/privileges.js
both/api/global-stats/server/publications.js
both/api/place-infos/server/methods.js
both/api/place-infos/server/pick-random-place-infos.js
both/api/source-imports/server/stats.js
both/api/sources/sources.js
client/lib/create-marker-from-feature.js
client/pages/sources/show/overview/initialize-map.js
client/pages/sources/show/overview/render-map.js
client/pages/startpage/page-start.html
client/pages/startpage/page-start.js
client/pages/startpage/page-start.less
client/pages/startpage/place-info.html
client/stylesheets/map.import.less

- Improved wording
- Show number of PoIs and sources (updated on every import)
- Show a new random place on the map every 5 seconds (picked from 25 random places that are picked and cached on server start)
For testing, it's best to set `isShownOnStartPage: true` on your Wheelmap data source (directly in the DB).

Better startpage

---

both/api/captchas/captchas.js
both/api/captchas/server/indexing.js
both/api/captchas/server/privileges.js
both/api/captchas/server/synced-cron.js
both/api/images/images.js
both/api/images/server/build-selector.js
both/api/images/server/indexing.js
both/api/images/server/json-api.js
both/api/images/server/object-id-filter.js
both/api/images/server/place-id-filter.js
both/api/images/server/privileges.js
both/api/images/server/save-upload-from-stream.js
package.json
server/captcha.js
server/hash-ip.js
server/image-upload.js
server/json-api/collections.js
server/throttle-api.js
settings/local-example.json

Added image upload API 
- Added image upload POST method
- Similar to file uploads
- Stores images in separate collection
- Allows linking to existing places
Added image listing API
- GET api for querying images for a place
- list of images with full s3 url
Added simple captcha service api
- API for querying captchas at /captcha.svg
- returns svg content
- Captcha data is stored in db with the generated solution
- Old Captchas are automatically removed after some time via cron job
- Image uploads require non-outdated captcha
- Matching same placeId, hashedIp, solution, appCode
Simple IP based throttling
- Only for captcha & upload image api
- Check timestamp & hashedIp for requests above a certain frequency
- Could be generalised into something for every api request

Image upload to replace wheelmap classics photo upload

---

both/api/images/images.js
both/api/images/server/json-api.js
both/api/images/server/methods.js
both/api/images/server/privileges.js
both/api/images/server/publications.js
both/api/images/server/save-upload-from-stream.js
client/pages/admin/admin-page.html
client/pages/admin/admin-page.js
client/pages/admin/admin-page.less
client/pages/admin/images/moderate-images.html
client/pages/admin/images/moderate-images.js
client/pages/admin/images/moderate-images.less
client/routes.js
server/browser-policy.js

- Display Images on admin page
- outstanding moderation queue badge
- Moderation interface
- basic filtering (date, ip, reported)
- basic paging (skip, limit)
- basic sorting (new, old)

Added moderation ui

---

both/api/images/images.js
both/api/images/server/json-api.js
both/api/images/server/methods.js
client/pages/admin/images/moderate-images.html
client/pages/admin/images/moderate-images.js
server/captcha.js
server/image-upload.js
server/json-api/authenticate-request.js
server/report-image.js

- POST /images/report will flag an image for moderation
- Fixed some smaller issues to have the round trip
"upload, moderate, report, moderate..."
work fine

Added report image API

---

README.md

docs/db-structure.md was deleted in c730936345af38408b26ddc49776faac18ddcde2

Remove outdated link from README

---

both/api/apps/server/publications.js
both/api/equipment-infos/server/add-sensor-token.js
both/api/place-infos/server/surrogate-keys.js
both/api/source-imports/server/publications.js
both/api/sources/server/stream-chain/object-progress-stream.js
both/i18n/locales.js
client/components/source/source.html
client/components/source/source.js
client/pages/apps/show.js
client/pages/sources/show/sidebar/charts/activity.js
server/i18n/displayStats.ts
server/i18n/exportToTransifex.ts
server/i18n/getDefaultTranslationStrategy.ts
server/i18n/getSupportedLocales.ts
server/i18n/syncCollectionWithTransifex.ts
server/i18n/updateAndPruneUnusedStringsFromPOFile.ts
server/json-api/json-api.js

- Improve logging for transifex syncing
- Fix mixed up `en_US`/`en` locales that happened because `en` resource on transifex had `en_US` in its header
- Fix adding local translations to transifex if they don’t exist there yet
- Fix cases where local translation was not set correctly if missing

Fix several more transifex issues that happened in app link i18n sync.

---

both/api/sources/server/stream-chain/generate-dynamic-url.js

- include time & date
- format as ISO to support mongo queries for eg.
kobo toolbox

Extended dynamic url to replace ISO date

---

both/api/images/server/save-upload-from-stream.js

Disabled images for moderation by default

---

both/api/global-stats/global-stats.js

This calculates stats for the whole attributes tree of all place infos and saves it into the DB.
This should be done periodically at some point, at it is missing a frontend.

Calculate global statistics

---

both/api/app-links/app-links.js
both/api/apps/apps.js
both/api/categories/categories.js
both/api/global-stats/global-stats.js
both/api/global-stats/server/rpc.js
both/api/languages/server/privileges.js
both/api/licenses/server/privileges.js
both/api/sources/server/privileges.js
both/api/sources/server/stream-chain/generate-dynamic-url.js

This fixes last import date insertion, global stats generation and non-working selectors for GET requests over the JSON API

3 bugfixes

---

both/api/accessibility-attributes/accessibility-attributes.js
both/api/accessibility-attributes/server/indexing.js
both/i18n/ac-format-translations.js

See new style change with sync button at https://github.com/sozialhelden/accessibility-apps/pull/6

Added accessibility-attributes to legacy

---

both/api/place-infos/server/build-selector.js
both/api/place-infos/server/indexing.js

- Aligned with the changes in https://github.com/sozialhelden/accessibility-apps/pull/12

Hide deleted places from rest api

---

both/api/sources/sources.js
package.json

Record equipment status (WIP)

---

README.md

add 4 line to README for testing
